//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CayGiong.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_SEED_FARMEntities : DbContext
    {
        public DB_SEED_FARMEntities()
            : base("name=DB_SEED_FARMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Order_detal> Order_detal { get; set; }
        public virtual DbSet<OrderProduct> OrderProducts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Status_Order> Status_Order { get; set; }
    
        public virtual ObjectResult<getCateParent_Result> getCateParent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCateParent_Result>("getCateParent");
        }
    
        public virtual ObjectResult<PR_Login_user_Result> PR_Login_user(string useName, string pass)
        {
            var useNameParameter = useName != null ?
                new ObjectParameter("useName", useName) :
                new ObjectParameter("useName", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_Login_user_Result>("PR_Login_user", useNameParameter, passParameter);
        }
    
        public virtual ObjectResult<PRgetIdParent_Result> PRgetIdParent(Nullable<int> idCate)
        {
            var idCateParameter = idCate.HasValue ?
                new ObjectParameter("idCate", idCate) :
                new ObjectParameter("idCate", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRgetIdParent_Result>("PRgetIdParent", idCateParameter);
        }
    
        public virtual ObjectResult<pr_RpTurnover_Result> pr_RpTurnover()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_RpTurnover_Result>("pr_RpTurnover");
        }
    
        public virtual ObjectResult<pr_RpTurnoverWithDay_Result> pr_RpTurnoverWithDay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_RpTurnoverWithDay_Result>("pr_RpTurnoverWithDay");
        }
    
        public virtual ObjectResult<CheckDel_Result> CheckDel(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CheckDel_Result>("CheckDel", idParameter);
        }
    
        public virtual ObjectResult<pr_RpTurnoverWithMonth_Result> pr_RpTurnoverWithMonth()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_RpTurnoverWithMonth_Result>("pr_RpTurnoverWithMonth");
        }
    }
}
