//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CayGiong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_detal
    {
        public int id_Order { get; set; }
        public int id_Product { get; set; }
        public int quantity { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual OrderProduct OrderProduct { get; set; }
        public virtual Product Product { get; set; }
    }
}
